/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVaultController } from "./IVaultController";
export type { VaultControllerEvents } from "./VaultControllerEvents";
