/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../common";

export interface ICurveMasterInterface extends utils.Interface {
  functions: {
    "getValueAt(address,int256)": FunctionFragment;
    "setCurve(address,address)": FunctionFragment;
    "setVaultController(address)": FunctionFragment;
    "vaultControllerAddress()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getValueAt"
      | "setCurve"
      | "setVaultController"
      | "vaultControllerAddress"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getValueAt",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setCurve",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setVaultController",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultControllerAddress",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "getValueAt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setCurve", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setVaultController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultControllerAddress",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ICurveMaster extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ICurveMasterInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getValueAt(
      curve_address: string,
      x_value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    setCurve(
      token_address: string,
      curve_address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setVaultController(
      vault_master_address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    vaultControllerAddress(overrides?: CallOverrides): Promise<[string]>;
  };

  getValueAt(
    curve_address: string,
    x_value: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setCurve(
    token_address: string,
    curve_address: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setVaultController(
    vault_master_address: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  vaultControllerAddress(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    getValueAt(
      curve_address: string,
      x_value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setCurve(
      token_address: string,
      curve_address: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setVaultController(
      vault_master_address: string,
      overrides?: CallOverrides
    ): Promise<void>;

    vaultControllerAddress(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    getValueAt(
      curve_address: string,
      x_value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setCurve(
      token_address: string,
      curve_address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setVaultController(
      vault_master_address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    vaultControllerAddress(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getValueAt(
      curve_address: string,
      x_value: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setCurve(
      token_address: string,
      curve_address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setVaultController(
      vault_master_address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    vaultControllerAddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
