/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { TokenDelegateStorageV1__factory } from "./TokenDelegateStorageV1__factory";
export { TokenDelegatorStorage__factory } from "./TokenDelegatorStorage__factory";
