/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export interface IVaultControllerInterface extends utils.Interface {
  functions: {
    "accountBorrowingPower(uint96)": FunctionFragment;
    "accountLiability(uint96)": FunctionFragment;
    "amountToSolvency(uint96)": FunctionFragment;
    "borrowUsdi(uint96,uint192)": FunctionFragment;
    "calculateInterest()": FunctionFragment;
    "changeProtocolFee(uint192)": FunctionFragment;
    "checkAccount(uint96)": FunctionFragment;
    "initialize()": FunctionFragment;
    "interestFactor()": FunctionFragment;
    "lastInterestTime()": FunctionFragment;
    "liquidateAccount(uint96,address,uint256)": FunctionFragment;
    "mintVault()": FunctionFragment;
    "pause()": FunctionFragment;
    "protocolFee()": FunctionFragment;
    "registerCurveMaster(address)": FunctionFragment;
    "registerErc20(address,uint256,address,uint256)": FunctionFragment;
    "registerOracleMaster(address)": FunctionFragment;
    "registerUSDi(address)": FunctionFragment;
    "repayAllUSDi(uint96)": FunctionFragment;
    "repayUSDi(uint96,uint192)": FunctionFragment;
    "tokensRegistered()": FunctionFragment;
    "tokensToLiquidate(uint96,address)": FunctionFragment;
    "totalBaseLiability()": FunctionFragment;
    "unpause()": FunctionFragment;
    "updateRegisteredErc20(address,uint256,address,uint256)": FunctionFragment;
    "vaultAddress(uint96)": FunctionFragment;
    "vaultsMinted()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "accountBorrowingPower"
      | "accountLiability"
      | "amountToSolvency"
      | "borrowUsdi"
      | "calculateInterest"
      | "changeProtocolFee"
      | "checkAccount"
      | "initialize"
      | "interestFactor"
      | "lastInterestTime"
      | "liquidateAccount"
      | "mintVault"
      | "pause"
      | "protocolFee"
      | "registerCurveMaster"
      | "registerErc20"
      | "registerOracleMaster"
      | "registerUSDi"
      | "repayAllUSDi"
      | "repayUSDi"
      | "tokensRegistered"
      | "tokensToLiquidate"
      | "totalBaseLiability"
      | "unpause"
      | "updateRegisteredErc20"
      | "vaultAddress"
      | "vaultsMinted"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "accountBorrowingPower",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "accountLiability",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "amountToSolvency",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "borrowUsdi",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "calculateInterest",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "changeProtocolFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkAccount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "interestFactor",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastInterestTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "liquidateAccount",
    values: [BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "mintVault", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerCurveMaster",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerErc20",
    values: [string, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerOracleMaster",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerUSDi",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "repayAllUSDi",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "repayUSDi",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokensRegistered",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "tokensToLiquidate",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "totalBaseLiability",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateRegisteredErc20",
    values: [string, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultAddress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultsMinted",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "accountBorrowingPower",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "accountLiability",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "amountToSolvency",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "borrowUsdi", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "calculateInterest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeProtocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "interestFactor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastInterestTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidateAccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintVault", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerCurveMaster",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerErc20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerOracleMaster",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerUSDi",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "repayAllUSDi",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repayUSDi", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tokensRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokensToLiquidate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalBaseLiability",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateRegisteredErc20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vaultsMinted",
    data: BytesLike
  ): Result;

  events: {
    "BorrowUSDi(uint256,address,uint256)": EventFragment;
    "InterestEvent(uint64,uint192,uint256)": EventFragment;
    "Liquidate(uint256,address,uint256,uint256)": EventFragment;
    "NewProtocolFee(uint256)": EventFragment;
    "NewVault(address,uint256,address)": EventFragment;
    "RegisterCurveMaster(address)": EventFragment;
    "RegisterOracleMaster(address)": EventFragment;
    "RegisteredErc20(address,uint256,address,uint256)": EventFragment;
    "RepayUSDi(uint256,address,uint256)": EventFragment;
    "UpdateRegisteredErc20(address,uint256,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BorrowUSDi"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "InterestEvent"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Liquidate"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewProtocolFee"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewVault"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RegisterCurveMaster"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RegisterOracleMaster"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RegisteredErc20"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RepayUSDi"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateRegisteredErc20"): EventFragment;
}

export interface BorrowUSDiEventObject {
  vaultId: BigNumber;
  vaultAddress: string;
  borrowAmount: BigNumber;
}
export type BorrowUSDiEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  BorrowUSDiEventObject
>;

export type BorrowUSDiEventFilter = TypedEventFilter<BorrowUSDiEvent>;

export interface InterestEventEventObject {
  epoch: BigNumber;
  amount: BigNumber;
  curve_val: BigNumber;
}
export type InterestEventEvent = TypedEvent<
  [BigNumber, BigNumber, BigNumber],
  InterestEventEventObject
>;

export type InterestEventEventFilter = TypedEventFilter<InterestEventEvent>;

export interface LiquidateEventObject {
  vaultId: BigNumber;
  asset_address: string;
  usdi_to_repurchase: BigNumber;
  tokens_to_liquidate: BigNumber;
}
export type LiquidateEvent = TypedEvent<
  [BigNumber, string, BigNumber, BigNumber],
  LiquidateEventObject
>;

export type LiquidateEventFilter = TypedEventFilter<LiquidateEvent>;

export interface NewProtocolFeeEventObject {
  protocol_fee: BigNumber;
}
export type NewProtocolFeeEvent = TypedEvent<
  [BigNumber],
  NewProtocolFeeEventObject
>;

export type NewProtocolFeeEventFilter = TypedEventFilter<NewProtocolFeeEvent>;

export interface NewVaultEventObject {
  vault_address: string;
  vaultId: BigNumber;
  vaultOwner: string;
}
export type NewVaultEvent = TypedEvent<
  [string, BigNumber, string],
  NewVaultEventObject
>;

export type NewVaultEventFilter = TypedEventFilter<NewVaultEvent>;

export interface RegisterCurveMasterEventObject {
  curveMasterAddress: string;
}
export type RegisterCurveMasterEvent = TypedEvent<
  [string],
  RegisterCurveMasterEventObject
>;

export type RegisterCurveMasterEventFilter =
  TypedEventFilter<RegisterCurveMasterEvent>;

export interface RegisterOracleMasterEventObject {
  oracleMasterAddress: string;
}
export type RegisterOracleMasterEvent = TypedEvent<
  [string],
  RegisterOracleMasterEventObject
>;

export type RegisterOracleMasterEventFilter =
  TypedEventFilter<RegisterOracleMasterEvent>;

export interface RegisteredErc20EventObject {
  token_address: string;
  LTVe4: BigNumber;
  oracle_address: string;
  liquidationIncentivee4: BigNumber;
}
export type RegisteredErc20Event = TypedEvent<
  [string, BigNumber, string, BigNumber],
  RegisteredErc20EventObject
>;

export type RegisteredErc20EventFilter = TypedEventFilter<RegisteredErc20Event>;

export interface RepayUSDiEventObject {
  vaultId: BigNumber;
  vaultAddress: string;
  repayAmount: BigNumber;
}
export type RepayUSDiEvent = TypedEvent<
  [BigNumber, string, BigNumber],
  RepayUSDiEventObject
>;

export type RepayUSDiEventFilter = TypedEventFilter<RepayUSDiEvent>;

export interface UpdateRegisteredErc20EventObject {
  token_address: string;
  LTVe4: BigNumber;
  oracle_address: string;
  liquidationIncentivee4: BigNumber;
}
export type UpdateRegisteredErc20Event = TypedEvent<
  [string, BigNumber, string, BigNumber],
  UpdateRegisteredErc20EventObject
>;

export type UpdateRegisteredErc20EventFilter =
  TypedEventFilter<UpdateRegisteredErc20Event>;

export interface IVaultController extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IVaultControllerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    accountBorrowingPower(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    accountLiability(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    amountToSolvency(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    borrowUsdi(
      id: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    calculateInterest(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    changeProtocolFee(
      new_protocol_fee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    checkAccount(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    interestFactor(overrides?: CallOverrides): Promise<[BigNumber]>;

    lastInterestTime(overrides?: CallOverrides): Promise<[BigNumber]>;

    liquidateAccount(
      id: BigNumberish,
      asset_address: string,
      tokenAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    mintVault(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    protocolFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    registerCurveMaster(
      master_curve_address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    registerErc20(
      token_address: string,
      LTV: BigNumberish,
      oracle_address: string,
      liquidationIncentive: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    registerOracleMaster(
      master_oracle_address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    registerUSDi(
      usdi_address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    repayAllUSDi(
      id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    repayUSDi(
      id: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    tokensRegistered(overrides?: CallOverrides): Promise<[BigNumber]>;

    tokensToLiquidate(
      id: BigNumberish,
      token: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    totalBaseLiability(overrides?: CallOverrides): Promise<[BigNumber]>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateRegisteredErc20(
      token_address: string,
      LTV: BigNumberish,
      oracle_address: string,
      liquidationIncentive: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    vaultAddress(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[string]>;

    vaultsMinted(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  accountBorrowingPower(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  accountLiability(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  amountToSolvency(
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  borrowUsdi(
    id: BigNumberish,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  calculateInterest(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  changeProtocolFee(
    new_protocol_fee: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  checkAccount(id: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

  initialize(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  interestFactor(overrides?: CallOverrides): Promise<BigNumber>;

  lastInterestTime(overrides?: CallOverrides): Promise<BigNumber>;

  liquidateAccount(
    id: BigNumberish,
    asset_address: string,
    tokenAmount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  mintVault(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  pause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  protocolFee(overrides?: CallOverrides): Promise<BigNumber>;

  registerCurveMaster(
    master_curve_address: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  registerErc20(
    token_address: string,
    LTV: BigNumberish,
    oracle_address: string,
    liquidationIncentive: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  registerOracleMaster(
    master_oracle_address: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  registerUSDi(
    usdi_address: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  repayAllUSDi(
    id: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  repayUSDi(
    id: BigNumberish,
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  tokensRegistered(overrides?: CallOverrides): Promise<BigNumber>;

  tokensToLiquidate(
    id: BigNumberish,
    token: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  totalBaseLiability(overrides?: CallOverrides): Promise<BigNumber>;

  unpause(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateRegisteredErc20(
    token_address: string,
    LTV: BigNumberish,
    oracle_address: string,
    liquidationIncentive: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  vaultAddress(id: BigNumberish, overrides?: CallOverrides): Promise<string>;

  vaultsMinted(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    accountBorrowingPower(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    accountLiability(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    amountToSolvency(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    borrowUsdi(
      id: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    calculateInterest(overrides?: CallOverrides): Promise<BigNumber>;

    changeProtocolFee(
      new_protocol_fee: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    checkAccount(id: BigNumberish, overrides?: CallOverrides): Promise<boolean>;

    initialize(overrides?: CallOverrides): Promise<void>;

    interestFactor(overrides?: CallOverrides): Promise<BigNumber>;

    lastInterestTime(overrides?: CallOverrides): Promise<BigNumber>;

    liquidateAccount(
      id: BigNumberish,
      asset_address: string,
      tokenAmount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    mintVault(overrides?: CallOverrides): Promise<string>;

    pause(overrides?: CallOverrides): Promise<void>;

    protocolFee(overrides?: CallOverrides): Promise<BigNumber>;

    registerCurveMaster(
      master_curve_address: string,
      overrides?: CallOverrides
    ): Promise<void>;

    registerErc20(
      token_address: string,
      LTV: BigNumberish,
      oracle_address: string,
      liquidationIncentive: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    registerOracleMaster(
      master_oracle_address: string,
      overrides?: CallOverrides
    ): Promise<void>;

    registerUSDi(
      usdi_address: string,
      overrides?: CallOverrides
    ): Promise<void>;

    repayAllUSDi(id: BigNumberish, overrides?: CallOverrides): Promise<void>;

    repayUSDi(
      id: BigNumberish,
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    tokensRegistered(overrides?: CallOverrides): Promise<BigNumber>;

    tokensToLiquidate(
      id: BigNumberish,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalBaseLiability(overrides?: CallOverrides): Promise<BigNumber>;

    unpause(overrides?: CallOverrides): Promise<void>;

    updateRegisteredErc20(
      token_address: string,
      LTV: BigNumberish,
      oracle_address: string,
      liquidationIncentive: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    vaultAddress(id: BigNumberish, overrides?: CallOverrides): Promise<string>;

    vaultsMinted(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    "BorrowUSDi(uint256,address,uint256)"(
      vaultId?: null,
      vaultAddress?: null,
      borrowAmount?: null
    ): BorrowUSDiEventFilter;
    BorrowUSDi(
      vaultId?: null,
      vaultAddress?: null,
      borrowAmount?: null
    ): BorrowUSDiEventFilter;

    "InterestEvent(uint64,uint192,uint256)"(
      epoch?: null,
      amount?: null,
      curve_val?: null
    ): InterestEventEventFilter;
    InterestEvent(
      epoch?: null,
      amount?: null,
      curve_val?: null
    ): InterestEventEventFilter;

    "Liquidate(uint256,address,uint256,uint256)"(
      vaultId?: null,
      asset_address?: null,
      usdi_to_repurchase?: null,
      tokens_to_liquidate?: null
    ): LiquidateEventFilter;
    Liquidate(
      vaultId?: null,
      asset_address?: null,
      usdi_to_repurchase?: null,
      tokens_to_liquidate?: null
    ): LiquidateEventFilter;

    "NewProtocolFee(uint256)"(protocol_fee?: null): NewProtocolFeeEventFilter;
    NewProtocolFee(protocol_fee?: null): NewProtocolFeeEventFilter;

    "NewVault(address,uint256,address)"(
      vault_address?: null,
      vaultId?: null,
      vaultOwner?: null
    ): NewVaultEventFilter;
    NewVault(
      vault_address?: null,
      vaultId?: null,
      vaultOwner?: null
    ): NewVaultEventFilter;

    "RegisterCurveMaster(address)"(
      curveMasterAddress?: null
    ): RegisterCurveMasterEventFilter;
    RegisterCurveMaster(
      curveMasterAddress?: null
    ): RegisterCurveMasterEventFilter;

    "RegisterOracleMaster(address)"(
      oracleMasterAddress?: null
    ): RegisterOracleMasterEventFilter;
    RegisterOracleMaster(
      oracleMasterAddress?: null
    ): RegisterOracleMasterEventFilter;

    "RegisteredErc20(address,uint256,address,uint256)"(
      token_address?: null,
      LTVe4?: null,
      oracle_address?: null,
      liquidationIncentivee4?: null
    ): RegisteredErc20EventFilter;
    RegisteredErc20(
      token_address?: null,
      LTVe4?: null,
      oracle_address?: null,
      liquidationIncentivee4?: null
    ): RegisteredErc20EventFilter;

    "RepayUSDi(uint256,address,uint256)"(
      vaultId?: null,
      vaultAddress?: null,
      repayAmount?: null
    ): RepayUSDiEventFilter;
    RepayUSDi(
      vaultId?: null,
      vaultAddress?: null,
      repayAmount?: null
    ): RepayUSDiEventFilter;

    "UpdateRegisteredErc20(address,uint256,address,uint256)"(
      token_address?: null,
      LTVe4?: null,
      oracle_address?: null,
      liquidationIncentivee4?: null
    ): UpdateRegisteredErc20EventFilter;
    UpdateRegisteredErc20(
      token_address?: null,
      LTVe4?: null,
      oracle_address?: null,
      liquidationIncentivee4?: null
    ): UpdateRegisteredErc20EventFilter;
  };

  estimateGas: {
    accountBorrowingPower(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    accountLiability(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    amountToSolvency(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    borrowUsdi(
      id: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    calculateInterest(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    changeProtocolFee(
      new_protocol_fee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    checkAccount(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    interestFactor(overrides?: CallOverrides): Promise<BigNumber>;

    lastInterestTime(overrides?: CallOverrides): Promise<BigNumber>;

    liquidateAccount(
      id: BigNumberish,
      asset_address: string,
      tokenAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    mintVault(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    protocolFee(overrides?: CallOverrides): Promise<BigNumber>;

    registerCurveMaster(
      master_curve_address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    registerErc20(
      token_address: string,
      LTV: BigNumberish,
      oracle_address: string,
      liquidationIncentive: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    registerOracleMaster(
      master_oracle_address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    registerUSDi(
      usdi_address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    repayAllUSDi(
      id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    repayUSDi(
      id: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    tokensRegistered(overrides?: CallOverrides): Promise<BigNumber>;

    tokensToLiquidate(
      id: BigNumberish,
      token: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    totalBaseLiability(overrides?: CallOverrides): Promise<BigNumber>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateRegisteredErc20(
      token_address: string,
      LTV: BigNumberish,
      oracle_address: string,
      liquidationIncentive: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    vaultAddress(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    vaultsMinted(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    accountBorrowingPower(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    accountLiability(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    amountToSolvency(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    borrowUsdi(
      id: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    calculateInterest(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    changeProtocolFee(
      new_protocol_fee: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    checkAccount(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    interestFactor(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lastInterestTime(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    liquidateAccount(
      id: BigNumberish,
      asset_address: string,
      tokenAmount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    mintVault(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    pause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    protocolFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registerCurveMaster(
      master_curve_address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    registerErc20(
      token_address: string,
      LTV: BigNumberish,
      oracle_address: string,
      liquidationIncentive: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    registerOracleMaster(
      master_oracle_address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    registerUSDi(
      usdi_address: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    repayAllUSDi(
      id: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    repayUSDi(
      id: BigNumberish,
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    tokensRegistered(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tokensToLiquidate(
      id: BigNumberish,
      token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    totalBaseLiability(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    unpause(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateRegisteredErc20(
      token_address: string,
      LTV: BigNumberish,
      oracle_address: string,
      liquidationIncentive: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    vaultAddress(
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    vaultsMinted(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
