/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface VotingVaultControllerInterface extends utils.Interface {
  functions: {
    "BPTvaultAddress(uint96)": FunctionFragment;
    "BPTvaultId(address)": FunctionFragment;
    "_CappedToken_underlying(address)": FunctionFragment;
    "_auraBal()": FunctionFragment;
    "_auraBooster()": FunctionFragment;
    "_auraLpData(address)": FunctionFragment;
    "_underlying_CappedToken(address)": FunctionFragment;
    "_vaultAddress_vaultId(address)": FunctionFragment;
    "_vaultBPTaddress_vaultId(address)": FunctionFragment;
    "_vaultController()": FunctionFragment;
    "_vaultId_vaultBPTaddress(uint96)": FunctionFragment;
    "_vaultId_votingVaultAddress(uint96)": FunctionFragment;
    "_votingVaultAddress_vaultId(address)": FunctionFragment;
    "getAuraLpData(address)": FunctionFragment;
    "initialize(address)": FunctionFragment;
    "mintBptVault(uint96)": FunctionFragment;
    "mintVault(uint96)": FunctionFragment;
    "owner()": FunctionFragment;
    "registerAuraBal(address)": FunctionFragment;
    "registerAuraBooster(address)": FunctionFragment;
    "registerAuraLpData(address,address,uint256)": FunctionFragment;
    "registerUnderlying(address,address)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "retrieveUnderlying(uint256,address,address)": FunctionFragment;
    "retrieveUnderlyingBPT(uint256,address,address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "vaultId(address)": FunctionFragment;
    "votingVaultAddress(uint96)": FunctionFragment;
    "votingVaultId(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "BPTvaultAddress"
      | "BPTvaultAddress(uint96)"
      | "BPTvaultId"
      | "BPTvaultId(address)"
      | "_CappedToken_underlying"
      | "_CappedToken_underlying(address)"
      | "_auraBal"
      | "_auraBal()"
      | "_auraBooster"
      | "_auraBooster()"
      | "_auraLpData"
      | "_auraLpData(address)"
      | "_underlying_CappedToken"
      | "_underlying_CappedToken(address)"
      | "_vaultAddress_vaultId"
      | "_vaultAddress_vaultId(address)"
      | "_vaultBPTaddress_vaultId"
      | "_vaultBPTaddress_vaultId(address)"
      | "_vaultController"
      | "_vaultController()"
      | "_vaultId_vaultBPTaddress"
      | "_vaultId_vaultBPTaddress(uint96)"
      | "_vaultId_votingVaultAddress"
      | "_vaultId_votingVaultAddress(uint96)"
      | "_votingVaultAddress_vaultId"
      | "_votingVaultAddress_vaultId(address)"
      | "getAuraLpData"
      | "getAuraLpData(address)"
      | "initialize"
      | "initialize(address)"
      | "mintBptVault"
      | "mintBptVault(uint96)"
      | "mintVault"
      | "mintVault(uint96)"
      | "owner"
      | "owner()"
      | "registerAuraBal"
      | "registerAuraBal(address)"
      | "registerAuraBooster"
      | "registerAuraBooster(address)"
      | "registerAuraLpData"
      | "registerAuraLpData(address,address,uint256)"
      | "registerUnderlying"
      | "registerUnderlying(address,address)"
      | "renounceOwnership"
      | "renounceOwnership()"
      | "retrieveUnderlying"
      | "retrieveUnderlying(uint256,address,address)"
      | "retrieveUnderlyingBPT"
      | "retrieveUnderlyingBPT(uint256,address,address)"
      | "transferOwnership"
      | "transferOwnership(address)"
      | "vaultId"
      | "vaultId(address)"
      | "votingVaultAddress"
      | "votingVaultAddress(uint96)"
      | "votingVaultId"
      | "votingVaultId(address)"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "BPTvaultAddress",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "BPTvaultAddress(uint96)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "BPTvaultId",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "BPTvaultId(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "_CappedToken_underlying",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "_CappedToken_underlying(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "_auraBal", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "_auraBal()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_auraBooster",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_auraBooster()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_auraLpData",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "_auraLpData(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "_underlying_CappedToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "_underlying_CappedToken(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "_vaultAddress_vaultId",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "_vaultAddress_vaultId(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "_vaultBPTaddress_vaultId",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "_vaultBPTaddress_vaultId(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "_vaultController",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_vaultController()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_vaultId_vaultBPTaddress",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "_vaultId_vaultBPTaddress(uint96)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "_vaultId_votingVaultAddress",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "_vaultId_votingVaultAddress(uint96)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "_votingVaultAddress_vaultId",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "_votingVaultAddress_vaultId(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuraLpData",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getAuraLpData(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "mintBptVault",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "mintBptVault(uint96)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "mintVault",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "mintVault(uint96)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner()", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAuraBal",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAuraBal(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAuraBooster",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAuraBooster(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAuraLpData",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAuraLpData(address,address,uint256)",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "registerUnderlying",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "registerUnderlying(address,address)",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "retrieveUnderlying",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "retrieveUnderlying(uint256,address,address)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "retrieveUnderlyingBPT",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "retrieveUnderlyingBPT(uint256,address,address)",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<string>,
      PromiseOrValue<string>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultId",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "vaultId(address)",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "votingVaultAddress",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "votingVaultAddress(uint96)",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "votingVaultId",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "votingVaultId(address)",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "BPTvaultAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "BPTvaultAddress(uint96)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "BPTvaultId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "BPTvaultId(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_CappedToken_underlying",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_CappedToken_underlying(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "_auraBal", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "_auraBal()", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "_auraBooster",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_auraBooster()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_auraLpData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_auraLpData(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_underlying_CappedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_underlying_CappedToken(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_vaultAddress_vaultId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_vaultAddress_vaultId(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_vaultBPTaddress_vaultId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_vaultBPTaddress_vaultId(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_vaultController",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_vaultController()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_vaultId_vaultBPTaddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_vaultId_vaultBPTaddress(uint96)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_vaultId_votingVaultAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_vaultId_votingVaultAddress(uint96)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_votingVaultAddress_vaultId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_votingVaultAddress_vaultId(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuraLpData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAuraLpData(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initialize(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintBptVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintBptVault(uint96)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintVault", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintVault(uint96)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner()", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAuraBal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAuraBal(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAuraBooster",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAuraBooster(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAuraLpData",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAuraLpData(address,address,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerUnderlying",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerUnderlying(address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retrieveUnderlying",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retrieveUnderlying(uint256,address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retrieveUnderlyingBPT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "retrieveUnderlyingBPT(uint256,address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vaultId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vaultId(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votingVaultAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votingVaultAddress(uint96)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votingVaultId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votingVaultId(address)",
    data: BytesLike
  ): Result;

  events: {
    "NewVaultBPT(address,uint256)": EventFragment;
    "NewVotingVault(address,uint256)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "NewVaultBPT"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "NewVaultBPT(address,uint256)"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "NewVotingVault"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "NewVotingVault(address,uint256)"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "OwnershipTransferred(address,address)"
  ): EventFragment;
}

export interface NewVaultBPTEventObject {
  vault_bpt_address: string;
  vaultId: BigNumber;
}
export type NewVaultBPTEvent = TypedEvent<
  [string, BigNumber],
  NewVaultBPTEventObject
>;

export type NewVaultBPTEventFilter = TypedEventFilter<NewVaultBPTEvent>;

export interface NewVotingVaultEventObject {
  voting_vault_address: string;
  vaultId: BigNumber;
}
export type NewVotingVaultEvent = TypedEvent<
  [string, BigNumber],
  NewVotingVaultEventObject
>;

export type NewVotingVaultEventFilter = TypedEventFilter<NewVotingVaultEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface VotingVaultController extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: VotingVaultControllerInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    BPTvaultAddress(
      vault_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "BPTvaultAddress(uint96)"(
      vault_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    BPTvaultId(
      vault_bpt_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "BPTvaultId(address)"(
      vault_bpt_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    _CappedToken_underlying(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "_CappedToken_underlying(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    _auraBal(overrides?: CallOverrides): Promise<[string]>;

    "_auraBal()"(overrides?: CallOverrides): Promise<[string]>;

    _auraBooster(overrides?: CallOverrides): Promise<[string]>;

    "_auraBooster()"(overrides?: CallOverrides): Promise<[string]>;

    _auraLpData(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { rewardToken: string; pid: BigNumber }>;

    "_auraLpData(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { rewardToken: string; pid: BigNumber }>;

    _underlying_CappedToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "_underlying_CappedToken(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    _vaultAddress_vaultId(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "_vaultAddress_vaultId(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    _vaultBPTaddress_vaultId(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "_vaultBPTaddress_vaultId(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    _vaultController(overrides?: CallOverrides): Promise<[string]>;

    "_vaultController()"(overrides?: CallOverrides): Promise<[string]>;

    _vaultId_vaultBPTaddress(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "_vaultId_vaultBPTaddress(uint96)"(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    _vaultId_votingVaultAddress(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "_vaultId_votingVaultAddress(uint96)"(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    _votingVaultAddress_vaultId(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "_votingVaultAddress_vaultId(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getAuraLpData(
      lp: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { rewardToken: string; pid: BigNumber }>;

    "getAuraLpData(address)"(
      lp: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { rewardToken: string; pid: BigNumber }>;

    initialize(
      vaultController_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "initialize(address)"(
      vaultController_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    mintBptVault(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "mintBptVault(uint96)"(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    mintVault(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "mintVault(uint96)"(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    registerAuraBal(
      auraBal: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "registerAuraBal(address)"(
      auraBal: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registerAuraBooster(
      newBooster: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "registerAuraBooster(address)"(
      newBooster: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registerAuraLpData(
      auraLP: PromiseOrValue<string>,
      rewardToken: PromiseOrValue<string>,
      pid: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "registerAuraLpData(address,address,uint256)"(
      auraLP: PromiseOrValue<string>,
      rewardToken: PromiseOrValue<string>,
      pid: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    registerUnderlying(
      underlying_address: PromiseOrValue<string>,
      capped_token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "registerUnderlying(address,address)"(
      underlying_address: PromiseOrValue<string>,
      capped_token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "renounceOwnership()"(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    retrieveUnderlying(
      amount: PromiseOrValue<BigNumberish>,
      voting_vault: PromiseOrValue<string>,
      target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "retrieveUnderlying(uint256,address,address)"(
      amount: PromiseOrValue<BigNumberish>,
      voting_vault: PromiseOrValue<string>,
      target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    retrieveUnderlyingBPT(
      amount: PromiseOrValue<BigNumberish>,
      vaultBPT: PromiseOrValue<string>,
      target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "retrieveUnderlyingBPT(uint256,address,address)"(
      amount: PromiseOrValue<BigNumberish>,
      vaultBPT: PromiseOrValue<string>,
      target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    vaultId(
      vault_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "vaultId(address)"(
      vault_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    votingVaultAddress(
      vault_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    "votingVaultAddress(uint96)"(
      vault_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    votingVaultId(
      voting_vault_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    "votingVaultId(address)"(
      voting_vault_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  BPTvaultAddress(
    vault_id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  "BPTvaultAddress(uint96)"(
    vault_id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  BPTvaultId(
    vault_bpt_address: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "BPTvaultId(address)"(
    vault_bpt_address: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  _CappedToken_underlying(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  "_CappedToken_underlying(address)"(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  _auraBal(overrides?: CallOverrides): Promise<string>;

  "_auraBal()"(overrides?: CallOverrides): Promise<string>;

  _auraBooster(overrides?: CallOverrides): Promise<string>;

  "_auraBooster()"(overrides?: CallOverrides): Promise<string>;

  _auraLpData(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { rewardToken: string; pid: BigNumber }>;

  "_auraLpData(address)"(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { rewardToken: string; pid: BigNumber }>;

  _underlying_CappedToken(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  "_underlying_CappedToken(address)"(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  _vaultAddress_vaultId(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "_vaultAddress_vaultId(address)"(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  _vaultBPTaddress_vaultId(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "_vaultBPTaddress_vaultId(address)"(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  _vaultController(overrides?: CallOverrides): Promise<string>;

  "_vaultController()"(overrides?: CallOverrides): Promise<string>;

  _vaultId_vaultBPTaddress(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  "_vaultId_vaultBPTaddress(uint96)"(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  _vaultId_votingVaultAddress(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  "_vaultId_votingVaultAddress(uint96)"(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  _votingVaultAddress_vaultId(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "_votingVaultAddress_vaultId(address)"(
    arg0: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getAuraLpData(
    lp: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { rewardToken: string; pid: BigNumber }>;

  "getAuraLpData(address)"(
    lp: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<[string, BigNumber] & { rewardToken: string; pid: BigNumber }>;

  initialize(
    vaultController_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "initialize(address)"(
    vaultController_: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  mintBptVault(
    id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "mintBptVault(uint96)"(
    id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  mintVault(
    id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "mintVault(uint96)"(
    id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  registerAuraBal(
    auraBal: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "registerAuraBal(address)"(
    auraBal: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registerAuraBooster(
    newBooster: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "registerAuraBooster(address)"(
    newBooster: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registerAuraLpData(
    auraLP: PromiseOrValue<string>,
    rewardToken: PromiseOrValue<string>,
    pid: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "registerAuraLpData(address,address,uint256)"(
    auraLP: PromiseOrValue<string>,
    rewardToken: PromiseOrValue<string>,
    pid: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  registerUnderlying(
    underlying_address: PromiseOrValue<string>,
    capped_token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "registerUnderlying(address,address)"(
    underlying_address: PromiseOrValue<string>,
    capped_token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "renounceOwnership()"(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  retrieveUnderlying(
    amount: PromiseOrValue<BigNumberish>,
    voting_vault: PromiseOrValue<string>,
    target: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "retrieveUnderlying(uint256,address,address)"(
    amount: PromiseOrValue<BigNumberish>,
    voting_vault: PromiseOrValue<string>,
    target: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  retrieveUnderlyingBPT(
    amount: PromiseOrValue<BigNumberish>,
    vaultBPT: PromiseOrValue<string>,
    target: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "retrieveUnderlyingBPT(uint256,address,address)"(
    amount: PromiseOrValue<BigNumberish>,
    vaultBPT: PromiseOrValue<string>,
    target: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  vaultId(
    vault_address: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "vaultId(address)"(
    vault_address: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  votingVaultAddress(
    vault_id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  "votingVaultAddress(uint96)"(
    vault_id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>;

  votingVaultId(
    voting_vault_address: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  "votingVaultId(address)"(
    voting_vault_address: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    BPTvaultAddress(
      vault_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    "BPTvaultAddress(uint96)"(
      vault_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    BPTvaultId(
      vault_bpt_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "BPTvaultId(address)"(
      vault_bpt_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _CappedToken_underlying(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    "_CappedToken_underlying(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    _auraBal(overrides?: CallOverrides): Promise<string>;

    "_auraBal()"(overrides?: CallOverrides): Promise<string>;

    _auraBooster(overrides?: CallOverrides): Promise<string>;

    "_auraBooster()"(overrides?: CallOverrides): Promise<string>;

    _auraLpData(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { rewardToken: string; pid: BigNumber }>;

    "_auraLpData(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { rewardToken: string; pid: BigNumber }>;

    _underlying_CappedToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    "_underlying_CappedToken(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    _vaultAddress_vaultId(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_vaultAddress_vaultId(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _vaultBPTaddress_vaultId(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_vaultBPTaddress_vaultId(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _vaultController(overrides?: CallOverrides): Promise<string>;

    "_vaultController()"(overrides?: CallOverrides): Promise<string>;

    _vaultId_vaultBPTaddress(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    "_vaultId_vaultBPTaddress(uint96)"(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    _vaultId_votingVaultAddress(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    "_vaultId_votingVaultAddress(uint96)"(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    _votingVaultAddress_vaultId(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_votingVaultAddress_vaultId(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAuraLpData(
      lp: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { rewardToken: string; pid: BigNumber }>;

    "getAuraLpData(address)"(
      lp: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string, BigNumber] & { rewardToken: string; pid: BigNumber }>;

    initialize(
      vaultController_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(address)"(
      vaultController_: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    mintBptVault(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    "mintBptVault(uint96)"(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    mintVault(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    "mintVault(uint96)"(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    registerAuraBal(
      auraBal: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    "registerAuraBal(address)"(
      auraBal: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    registerAuraBooster(
      newBooster: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    "registerAuraBooster(address)"(
      newBooster: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    registerAuraLpData(
      auraLP: PromiseOrValue<string>,
      rewardToken: PromiseOrValue<string>,
      pid: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    "registerAuraLpData(address,address,uint256)"(
      auraLP: PromiseOrValue<string>,
      rewardToken: PromiseOrValue<string>,
      pid: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    registerUnderlying(
      underlying_address: PromiseOrValue<string>,
      capped_token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    "registerUnderlying(address,address)"(
      underlying_address: PromiseOrValue<string>,
      capped_token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    retrieveUnderlying(
      amount: PromiseOrValue<BigNumberish>,
      voting_vault: PromiseOrValue<string>,
      target: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    "retrieveUnderlying(uint256,address,address)"(
      amount: PromiseOrValue<BigNumberish>,
      voting_vault: PromiseOrValue<string>,
      target: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    retrieveUnderlyingBPT(
      amount: PromiseOrValue<BigNumberish>,
      vaultBPT: PromiseOrValue<string>,
      target: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    "retrieveUnderlyingBPT(uint256,address,address)"(
      amount: PromiseOrValue<BigNumberish>,
      vaultBPT: PromiseOrValue<string>,
      target: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    vaultId(
      vault_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "vaultId(address)"(
      vault_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    votingVaultAddress(
      vault_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    "votingVaultAddress(uint96)"(
      vault_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>;

    votingVaultId(
      voting_vault_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "votingVaultId(address)"(
      voting_vault_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {
    "NewVaultBPT(address,uint256)"(
      vault_bpt_address?: null,
      vaultId?: null
    ): NewVaultBPTEventFilter;
    NewVaultBPT(
      vault_bpt_address?: null,
      vaultId?: null
    ): NewVaultBPTEventFilter;

    "NewVotingVault(address,uint256)"(
      voting_vault_address?: null,
      vaultId?: null
    ): NewVotingVaultEventFilter;
    NewVotingVault(
      voting_vault_address?: null,
      vaultId?: null
    ): NewVotingVaultEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    BPTvaultAddress(
      vault_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "BPTvaultAddress(uint96)"(
      vault_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    BPTvaultId(
      vault_bpt_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "BPTvaultId(address)"(
      vault_bpt_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _CappedToken_underlying(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_CappedToken_underlying(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _auraBal(overrides?: CallOverrides): Promise<BigNumber>;

    "_auraBal()"(overrides?: CallOverrides): Promise<BigNumber>;

    _auraBooster(overrides?: CallOverrides): Promise<BigNumber>;

    "_auraBooster()"(overrides?: CallOverrides): Promise<BigNumber>;

    _auraLpData(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_auraLpData(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _underlying_CappedToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_underlying_CappedToken(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _vaultAddress_vaultId(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_vaultAddress_vaultId(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _vaultBPTaddress_vaultId(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_vaultBPTaddress_vaultId(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _vaultController(overrides?: CallOverrides): Promise<BigNumber>;

    "_vaultController()"(overrides?: CallOverrides): Promise<BigNumber>;

    _vaultId_vaultBPTaddress(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_vaultId_vaultBPTaddress(uint96)"(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _vaultId_votingVaultAddress(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_vaultId_votingVaultAddress(uint96)"(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _votingVaultAddress_vaultId(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "_votingVaultAddress_vaultId(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getAuraLpData(
      lp: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getAuraLpData(address)"(
      lp: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    initialize(
      vaultController_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "initialize(address)"(
      vaultController_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    mintBptVault(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "mintBptVault(uint96)"(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    mintVault(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "mintVault(uint96)"(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    registerAuraBal(
      auraBal: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "registerAuraBal(address)"(
      auraBal: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registerAuraBooster(
      newBooster: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "registerAuraBooster(address)"(
      newBooster: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registerAuraLpData(
      auraLP: PromiseOrValue<string>,
      rewardToken: PromiseOrValue<string>,
      pid: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "registerAuraLpData(address,address,uint256)"(
      auraLP: PromiseOrValue<string>,
      rewardToken: PromiseOrValue<string>,
      pid: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    registerUnderlying(
      underlying_address: PromiseOrValue<string>,
      capped_token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "registerUnderlying(address,address)"(
      underlying_address: PromiseOrValue<string>,
      capped_token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "renounceOwnership()"(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    retrieveUnderlying(
      amount: PromiseOrValue<BigNumberish>,
      voting_vault: PromiseOrValue<string>,
      target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "retrieveUnderlying(uint256,address,address)"(
      amount: PromiseOrValue<BigNumberish>,
      voting_vault: PromiseOrValue<string>,
      target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    retrieveUnderlyingBPT(
      amount: PromiseOrValue<BigNumberish>,
      vaultBPT: PromiseOrValue<string>,
      target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "retrieveUnderlyingBPT(uint256,address,address)"(
      amount: PromiseOrValue<BigNumberish>,
      vaultBPT: PromiseOrValue<string>,
      target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    vaultId(
      vault_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "vaultId(address)"(
      vault_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    votingVaultAddress(
      vault_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "votingVaultAddress(uint96)"(
      vault_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    votingVaultId(
      voting_vault_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "votingVaultId(address)"(
      voting_vault_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    BPTvaultAddress(
      vault_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "BPTvaultAddress(uint96)"(
      vault_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    BPTvaultId(
      vault_bpt_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "BPTvaultId(address)"(
      vault_bpt_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _CappedToken_underlying(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_CappedToken_underlying(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _auraBal(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "_auraBal()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _auraBooster(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "_auraBooster()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    _auraLpData(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_auraLpData(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _underlying_CappedToken(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_underlying_CappedToken(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _vaultAddress_vaultId(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_vaultAddress_vaultId(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _vaultBPTaddress_vaultId(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_vaultBPTaddress_vaultId(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _vaultController(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "_vaultController()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _vaultId_vaultBPTaddress(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_vaultId_vaultBPTaddress(uint96)"(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _vaultId_votingVaultAddress(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_vaultId_votingVaultAddress(uint96)"(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _votingVaultAddress_vaultId(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "_votingVaultAddress_vaultId(address)"(
      arg0: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getAuraLpData(
      lp: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getAuraLpData(address)"(
      lp: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    initialize(
      vaultController_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "initialize(address)"(
      vaultController_: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    mintBptVault(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "mintBptVault(uint96)"(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    mintVault(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "mintVault(uint96)"(
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    registerAuraBal(
      auraBal: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "registerAuraBal(address)"(
      auraBal: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registerAuraBooster(
      newBooster: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "registerAuraBooster(address)"(
      newBooster: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registerAuraLpData(
      auraLP: PromiseOrValue<string>,
      rewardToken: PromiseOrValue<string>,
      pid: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "registerAuraLpData(address,address,uint256)"(
      auraLP: PromiseOrValue<string>,
      rewardToken: PromiseOrValue<string>,
      pid: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    registerUnderlying(
      underlying_address: PromiseOrValue<string>,
      capped_token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "registerUnderlying(address,address)"(
      underlying_address: PromiseOrValue<string>,
      capped_token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "renounceOwnership()"(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    retrieveUnderlying(
      amount: PromiseOrValue<BigNumberish>,
      voting_vault: PromiseOrValue<string>,
      target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "retrieveUnderlying(uint256,address,address)"(
      amount: PromiseOrValue<BigNumberish>,
      voting_vault: PromiseOrValue<string>,
      target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    retrieveUnderlyingBPT(
      amount: PromiseOrValue<BigNumberish>,
      vaultBPT: PromiseOrValue<string>,
      target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "retrieveUnderlyingBPT(uint256,address,address)"(
      amount: PromiseOrValue<BigNumberish>,
      vaultBPT: PromiseOrValue<string>,
      target: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    vaultId(
      vault_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "vaultId(address)"(
      vault_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    votingVaultAddress(
      vault_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "votingVaultAddress(uint96)"(
      vault_id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    votingVaultId(
      voting_vault_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "votingVaultId(address)"(
      voting_vault_address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
