/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iusdiSol from "./IUSDI.sol";
export * as external from "./_external";
export * as curve from "./curve";
export * as genesis from "./genesis";
export * as governance from "./governance";
export * as lending from "./lending";
export * as oracle from "./oracle";
export * as token from "./token";
export { USDI__factory } from "./USDI__factory";
