/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iTokenSol from "./IToken.sol";
export type { iTokenSol };
import type * as tokenDelegateSol from "./TokenDelegate.sol";
export type { tokenDelegateSol };
import type * as tokenDelegatorSol from "./TokenDelegator.sol";
export type { tokenDelegatorSol };
import type * as tokenStorageSol from "./TokenStorage.sol";
export type { tokenStorageSol };
